// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// GenerateUUIDInterface is an autogenerated mock type for the GenerateUUIDInterface type
type GenerateUUIDInterface struct {
	mock.Mock
}

// GenerateUUID provides a mock function with given fields:
func (_m *GenerateUUIDInterface) GenerateUUID() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// NewGenerateUUIDInterface creates a new instance of GenerateUUIDInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerateUUIDInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenerateUUIDInterface {
	mock := &GenerateUUIDInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
